#!/bin/bash

per_page=100
max_offset=48200

mkdir -p data.tags

for offset in `seq 0 100 $max_offset` ; do
  echo ">>> $offset / $max_offset"
  curl 'https://public-api.wordpress.com/wp/v2/sites/156670177/tags?offset='${offset}'&per_page='${per_page} > data.tags/tags_s${offset}.json
done
