#!/usr/bin/python3
#
# License: CC0
#

import os, re, sys
from datetime import datetime
import pytz
import json
import time
import bs4
import html
import cgi
#from bs4 import BeautifulSoup


# guid key
#
rss_db = {}

state = {
  "update":True
}

sleepy_s = 10.0

with open("rss-feed-config.json") as fp:
  cfg = json.loads(fp.read())


def entry_sort(e):
  return e["unixtime"]

def html_make_entry(ent):

  m = 1024

  s = "<li>"
  s += "<a class='feed_ico' href='" + str(ent["guid"]) + "'><img style='width:16px;' src='" + ent["icon"] + "'></a> "

  s += "<a href='" + ent["link"] + "'>" + html.escape(str(ent["title"])).encode('ascii', 'xmlcharrefreplace').decode('utf-8') + "</a>"

  s += "<small class='feed_datetime'>" + str(datetime.utcfromtimestamp(int(ent["unixtime"])).strftime("%Y-%m-%d %H:%M")) + "</small> "
  s+= "</li>"

  return s


def html_page(content):

  tz_utc = pytz.timezone("UTC")
  tz_pst = pytz.timezone("PST8PDT")
  tz_edt = pytz.timezone("EST5EDT")
  tz_cet = pytz.timezone("CET")
  tz_cdt = pytz.timezone("CST6CDT")

  dt_utc = datetime.now(tz_utc).strftime("%Y-%m-%d %H:%M:%S %Z")
  dt_pst = datetime.now(tz_pst).strftime("%Y-%m-%d %H:%M:%S %Z")
  dt_edt = datetime.now(tz_edt).strftime("%Y-%m-%d %H:%M:%S %Z")
  dt_cet = datetime.now(tz_cet).strftime("%Y-%m-%d %H:%M:%S %Z")
  dt_cdt = datetime.now(tz_cdt).strftime("%Y-%m-%d %H:%M:%S %Z")

  #_now = datetime.now()
  #dt = _now.strftime("%Y-%m-%d %H:%M:%S")

  s =  "<!doctype html>\n"
  s += "<html>\n"

  s += " <head>\n"
  s += "  <link rel='stylesheet' href='css/feed-styles.css'>\n"
  s += "  <link rel='stylesheet' href='css/pygment_trac.css'>\n"

  s += " </head>\n"

  s += " <body>\n"
  #s += "  <h1>feed <small>last updated: " + dt + "</small></h1>\n"

  s += "  <table>\n"
  s += "    <tr>\n"
  s += "      <td><h1>feed</h1></td>\n"
  s += "      <td> <small>" + dt_utc + "</small> </td>\n"
  s += "      <td> <small>" + dt_pst + "</small> </td>\n"
  s += "      <td> <small>" + dt_edt + "</small> </td>\n"
  s += "      <td> <small>" + dt_cet + "</small> </td>\n"
  s += "      <td> <small>" + dt_cdt + "</small> </td>\n"
  s += "    </tr>\n"
  s += "  </table>\n"

  s += "    <ul>\n"
  s += content
  s += "    </ul>\n"
  s += " </body>\n"

  s += " <script src='js/scale.fix.js'></script>"

  s += "</html>\n"

  return s

while True:

  new_entry = {}
  snapshot = {}

  for rss_ent in cfg["rss"]:
    url = rss_ent["url"]
    prs = rss_ent["parser"]

    stream = os.popen(cfg["parser"] + "/" + prs + " " +  url)
    ajson = stream.read()

    for line in ajson.split("\n"):
      line = line.strip()
      if len(line) == 0: continue
      if line[0] == '#': continue
      x = json.loads(line)

      dt_fmt = "%a, %d %b %Y %H:%M:%S %z"

      tok = x["pubDate"].split(" ")
      if (len(tok)==1):
        print("#debug:", x["pubDate"])

        x["pubDate"] = re.sub(r':(\d\d)$', '\\1', x["pubDate"])

        if re.search('\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d[+-]\d\d:?\d\d', x['pubDate']):
          dt_fmt = "%Y-%m-%dT%H:%M:%S%z"
        elif re.search('\d\d\d\d-\d\d-\d\dT\d\d:\d\d[+-]\d\d:?\d\d', x['pubDate']):
          dt_fmt = "%Y-%m-%dT%H:%M%z"

      elif (len(tok[5]) > 0) and (tok[5][0] != '-') and (tok[5][0] != '+'):
        dt_fmt = "%a, %d %b %Y %H:%M:%S %Z"

      x["unixtime"] = float(datetime.strptime(x["pubDate"], dt_fmt).strftime("%s"))

      x["icon"] = rss_ent["icon"]

      snapshot[ x["guid"] ] = x

      if not (x["guid"] in rss_db):
        new_entry[ x["guid"] ] = x
        rss_db[ x["guid"] ] = x

      x["html_entry"] = html_make_entry(x)

  guids = []
  for guid in rss_db:
    guids.append(guid)

  for guid in guids:
    if not (guid in snapshot):

      print("[" + str(time.time()) + "]" "removing " + str(guid))
      del rss_db[guid]

  print("[" + str(time.time()) + "]", "GOT new entries " + str(len(new_entry)))

  if len(new_entry) > 0:

    print("[" + str(time.time()) + "]", "UPDATING")

    ## sort entries
    ##
    _content_l = []
    for guid in snapshot:
      _content_l.append( snapshot[guid] )
    content_l = []
    if len(_content_l) > 0:
      _content_l.sort(key = entry_sort, reverse=True)
      content_l = map( lambda _x: _x["html_entry"], _content_l )

    _now = datetime.now()
    dt = _now.strftime("%Y-%m-%d_%H:%M:%S")
    dtd = _now.strftime("%Y-%m-%d")
    os.system("mkdir -p " + cfg["historic"] + "/" + dtd)

    html_fn = cfg["historic"] + "/" + str(dtd) + "/" + dt
    tmp_fn = "/tmp/" + dt
    with open(html_fn, "w") as fp:
      fp.write(html_page("\n".join(content_l)))

    os.system("cp " + html_fn + " " + tmp_fn)
    os.system("mv " + tmp_fn + " " + cfg["index"])

  print("[" + str(time.time()) + "]", "sleep " + str(sleepy_s))
  time.sleep(sleepy_s)
