#!/bin/bash

feed="$1"

if [[ "$feed" == "" ]] ; then
  echo "provide rss feed"
  exit 1
fi

wget -q "$feed" -O - | \
  xmltojson | \
  jq -c \
    '.rss.channel.item[] | { "feed": "'$feed'", "guid":.guid["$t"], "title" : .title, "link":.link, "description":.description, "content":.["content:encoded"], "pubDate":.pubDate } '


